"""Agent security errors — POST-RC-010."""

from __future__ import annotations

from enum import StrEnum


class AgentSecurityErrorCode(StrEnum):
    INVALID = "AGENT_SECURITY_INVALID"
    SNAPSHOT_MISMATCH = "AGENT_SECURITY_SNAPSHOT_MISMATCH"
    STALE_SNAPSHOT = "AGENT_SECURITY_STALE_SNAPSHOT"
    CROSS_AUDIT = "AGENT_SECURITY_CROSS_AUDIT"
    CROSS_PROJECT = "AGENT_SECURITY_CROSS_PROJECT"
    CROSS_SNAPSHOT = "AGENT_SECURITY_CROSS_SNAPSHOT"
    AUTHORITY_LANGUAGE = "AGENT_SECURITY_AUTHORITY_LANGUAGE"
    VERDICT_CAPPED = "AGENT_SECURITY_VERDICT_CAPPED"
    QUERY_REJECTED = "AGENT_SECURITY_QUERY_REJECTED"
    BUDGET_EXCEEDED = "AGENT_SECURITY_BUDGET_EXCEEDED"
    VERIFICATION_STALE = "AGENT_SECURITY_VERIFICATION_STALE"
    EVIDENCE_GAP = "AGENT_SECURITY_EVIDENCE_GAP"
    SECRET_MATERIAL = "AGENT_SECURITY_SECRET_MATERIAL"


class AgentSecurityError(Exception):
    def __init__(self, code: AgentSecurityErrorCode, message: str):
        super().__init__(f"{code.value}: {message}")
        self.code = code
