"""Finding Lifecycle & Security Classification — ECA-T011.

Evidence → Observation → Hypothesis → FindingCandidate → Verification
→ Finding. The path is never shortened: no CANDIDATE → CONFIRMED jump
without verification evidence, no CANDIDATE → REPORTED without
eligibility, and no model text ever becomes a Finding directly.

A Finding is an Evidence-backed, Verification-backed, Core-governed,
auditable security record — never prose generated by a model.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from emo_cyber_agent.core.correlation import FindingCandidate
from emo_cyber_agent.core.verification import assess_candidate  # verification-level assessment, re-exported for the finding path

__all__ = ["assess_candidate"]

CLASSIFICATION_VERSION = "cls-v1"
FINDING_SCHEMA_VERSION = "0.1.0"


class FindingStatus(StrEnum):
    CANDIDATE = "candidate"
    TRIAGED = "triaged"
    VERIFIED = "verified"
    CONFIRMED = "confirmed"
    REPORTED = "reported"
    RESOLVED = "resolved"
    DISPUTED = "disputed"
    REFUTED = "refuted"
    SUPPRESSED = "suppressed"
    DUPLICATE = "duplicate"
    INCONCLUSIVE = "inconclusive"


class Severity(StrEnum):
    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class FindingTaxonomy(StrEnum):
    AUTHENTICATION = "authentication"
    AUTHORIZATION = "authorization"
    INJECTION = "injection"
    CRYPTOGRAPHY = "cryptography"
    SECRETS = "secrets"
    DEPENDENCY = "dependency"
    SUPPLY_CHAIN = "supply_chain"
    DATA_EXPOSURE = "data_exposure"
    CONFIGURATION = "configuration"
    API_SECURITY = "api_security"
    RLS = "rls"
    BUSINESS_LOGIC = "business_logic"
    INFRASTRUCTURE = "infrastructure"
    SESSION = "session"
    INPUT_VALIDATION = "input_validation"
    OTHER = "other"


class Eligibility(StrEnum):
    ELIGIBLE = "eligible"
    NOT_ELIGIBLE = "not_eligible"
    NEEDS_REVIEW = "needs_review"


# Lifecycle: forward flow plus explicit alternative terminals. No shortcuts.
_FINDING_TRANSITIONS: dict[FindingStatus, frozenset[FindingStatus]] = {
    FindingStatus.CANDIDATE: frozenset({FindingStatus.TRIAGED, FindingStatus.DUPLICATE, FindingStatus.INCONCLUSIVE}),
    FindingStatus.TRIAGED: frozenset({FindingStatus.VERIFIED, FindingStatus.DISPUTED, FindingStatus.SUPPRESSED, FindingStatus.DUPLICATE, FindingStatus.INCONCLUSIVE}),
    FindingStatus.VERIFIED: frozenset({FindingStatus.CONFIRMED, FindingStatus.REFUTED, FindingStatus.DISPUTED, FindingStatus.INCONCLUSIVE}),
    FindingStatus.CONFIRMED: frozenset({FindingStatus.REPORTED, FindingStatus.DISPUTED, FindingStatus.RESOLVED}),
    FindingStatus.REPORTED: frozenset({FindingStatus.RESOLVED, FindingStatus.DISPUTED, FindingStatus.SUPPRESSED}),
    FindingStatus.RESOLVED: frozenset(),
    FindingStatus.DISPUTED: frozenset({FindingStatus.TRIAGED, FindingStatus.VERIFIED, FindingStatus.INCONCLUSIVE}),
    FindingStatus.REFUTED: frozenset(),
    FindingStatus.SUPPRESSED: frozenset({FindingStatus.TRIAGED}),
    FindingStatus.DUPLICATE: frozenset(),
    FindingStatus.INCONCLUSIVE: frozenset({FindingStatus.TRIAGED}),
}


def transition_finding(current: FindingStatus, new: FindingStatus) -> FindingStatus:
    if new not in _FINDING_TRANSITIONS[current]:
        raise ValueError(f"invalid finding transition {current.value} → {new.value}")
    return new


class SeverityAssessment(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    severity: Severity
    basis: str = Field(..., min_length=1)
    source: str = Field(..., min_length=1)
    rule_version: str = Field(default=CLASSIFICATION_VERSION)
    assessed_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class ConfidenceAssessment(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    value: float = Field(..., ge=0.0, le=1.0)
    evidence_count: int = Field(default=0, ge=0)
    independent_sources: int = Field(default=0, ge=0)
    verification_strength: str = ""
    contradiction_present: bool = False
    basis: str = ""


class Classification(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    category: FindingTaxonomy
    severity: SeverityAssessment
    confidence: ConfidenceAssessment
    cwe: str | None = None
    owasp: str | None = None
    cvss_vector: str | None = None
    cvss_score: float | None = Field(default=None, ge=0.0, le=10.0)
    cvss_source: str | None = None
    classification_version: str = Field(default=CLASSIFICATION_VERSION)
    explained: str = ""


class ClassificationConflict(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    assessments: tuple[SeverityAssessment, ...]
    note: str = ""


class Remediation(BaseModel):
    """Structured recommendation DATA. Never executed by Core."""

    model_config = ConfigDict(frozen=True, extra="forbid")
    recommendation: str = Field(..., min_length=1)
    affected_component: str = ""
    remediation_type: str = ""
    validation_guidance: str = ""


class SuppressionRecord(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    reason: str = Field(..., min_length=1)
    actor: str = Field(..., min_length=1)  # human/policy/system — never model
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    scope: str = ""
    expires_at: str | None = None

    @field_validator("actor")
    @classmethod
    def _no_model_actor(cls, v: str) -> str:
        if v.strip().lower() in ("model", "llm", "reasoner", "ai"):
            raise ValueError("model cannot suppress findings")
        return v


class SecurityFinding(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    finding_id: str = Field(..., min_length=1)
    audit_id: str = Field(..., min_length=1)
    asset_id: str | None = None
    title: str = Field(..., min_length=1)
    description: str = Field(..., min_length=1)
    category: FindingTaxonomy
    severity: Severity
    confidence: float = Field(..., ge=0.0, le=1.0)
    status: FindingStatus = FindingStatus.CANDIDATE
    cwe: str | None = None
    owasp: str | None = None
    affected_locations: tuple[str, ...] = ()
    evidence_ids: tuple[str, ...] = ()
    observation_ids: tuple[str, ...] = ()
    candidate_id: str = Field(..., min_length=1)
    verification_ids: tuple[str, ...] = ()
    first_seen: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    last_seen: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    provenance: dict[str, Any] = Field(default_factory=dict)
    remediation: Remediation | None = None
    references: tuple[str, ...] = ()
    suppression: SuppressionRecord | None = None
    # root-cause separation: unknown impact stays UNASSESSED, never invented
    observed_issue: str = ""
    root_cause: str = ""
    impact: str = "UNASSESSED"
    attack_precondition: str = ""
    fingerprint: str = ""
    regression_key: str = ""

    def transition_to(self, new: FindingStatus) -> SecurityFinding:
        transition_finding(self.status, new)
        return SecurityFinding(**{**self.model_dump(), "status": new, "last_seen": datetime.now(timezone.utc).isoformat()})


# ---------------------------------------------------------------------------
# Identity & dedup (audit-bound; regression keys link history only)
# ---------------------------------------------------------------------------

def finding_fingerprint(*, audit_id: str, asset_id: str | None, category: str, location: str, identity: str, rule: str) -> str:
    base = "|".join([audit_id, asset_id or "", category, location, identity, rule])
    return hashlib.sha256(base.encode("utf-8", errors="replace")).hexdigest()


def regression_key(*, asset_id: str | None, category: str, location: str, identity: str, rule: str) -> str:
    """Cross-audit history link. Carries NO evidence and merges nothing."""
    base = "|".join(["regression", asset_id or "", category, location, identity, rule])
    return hashlib.sha256(base.encode("utf-8", errors="replace")).hexdigest()


class FindingStore:
    """Audit-scoped finding registry with deterministic dedup."""

    def __init__(self) -> None:
        self._items: dict[str, SecurityFinding] = {}
        self._audit_of: dict[str, str] = {}
        self._by_fingerprint: dict[str, str] = {}

    def add(self, finding: SecurityFinding) -> SecurityFinding:
        """Dedup within one audit: same fingerprint returns the ORIGINAL as
        canonical and records the newcomer as DUPLICATE (never merged)."""
        if not finding.evidence_ids:
            raise ValueError("finding without evidence denied")
        existing_id = self._by_fingerprint.get(finding.fingerprint)
        if existing_id is not None and self._audit_of.get(existing_id) == finding.audit_id:
            canonical = self._items[existing_id]
            dup = SecurityFinding(**{**finding.model_dump(), "status": FindingStatus.DUPLICATE, "provenance": {**finding.provenance, "duplicate_of": existing_id}})
            self._items[dup.finding_id] = dup
            self._audit_of[dup.finding_id] = dup.audit_id
            return canonical
        self._items[finding.finding_id] = finding
        self._audit_of[finding.finding_id] = finding.audit_id
        if finding.fingerprint:
            self._by_fingerprint[finding.fingerprint] = finding.finding_id
        return finding

    def get(self, finding_id: str, *, audit_id: str) -> SecurityFinding:
        if self._audit_of.get(finding_id) != audit_id:
            raise KeyError(f"finding not in audit scope: {finding_id}")
        return self._items[finding_id]

    def list(self, *, audit_id: str) -> list[SecurityFinding]:
        return [f for fid, f in self._items.items() if self._audit_of.get(fid) == audit_id]


# ---------------------------------------------------------------------------
# Eligibility (deterministic; no LLM)
# ---------------------------------------------------------------------------

class EligibilityResult(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    verdict: Eligibility
    reasons: tuple[str, ...] = ()


def evaluate_finding_eligibility(
    *,
    candidate: FindingCandidate,
    evidence_ids: list[str],
    provenance_ok: bool,
    scope_ok: bool,
    verification_status: str,
    contradiction_unresolved: bool,
    candidate_status: str,
    policy_ok: bool,
    min_evidence: int = 1,
) -> EligibilityResult:
    reasons: list[str] = []
    if len(evidence_ids) < min_evidence:
        reasons.append("missing-evidence")
    if not provenance_ok:
        reasons.append("invalid-provenance")
    if not scope_ok:
        reasons.append("scope-mismatch")
    if verification_status not in ("confirmed", "supported"):
        reasons.append("unverified-candidate")
    if contradiction_unresolved:
        reasons.append("unresolved-contradiction")
    if candidate_status not in ("correlated", "supported", "verifying", "needs_verification"):
        reasons.append("bad-candidate-state")
    if not policy_ok:
        reasons.append("policy-denied")
    if not reasons:
        return EligibilityResult(verdict=Eligibility.ELIGIBLE, reasons=("criteria-met",))
    if set(reasons) <= {"unverified-candidate"}:
        return EligibilityResult(verdict=Eligibility.NEEDS_REVIEW, reasons=tuple(reasons))
    return EligibilityResult(verdict=Eligibility.NOT_ELIGIBLE, reasons=tuple(reasons))


# ---------------------------------------------------------------------------
# Deterministic classification (rules cls-v1; model suggests, Core decides)
# ---------------------------------------------------------------------------

_SEVERITY_ORDER = ["info", "low", "medium", "high", "critical"]

# Sparse static maps with recorded provenance. Unknown → null (never invented).
CWE_MAP: dict[str, str] = {
    "R1-auth-weakness": "CWE-639",
    "R3-secret-exposure": "CWE-798",
}
OWASP_MAP: dict[str, str] = {
    "R1-auth-weakness": "A01:2021-Broken Access Control",
    "R3-secret-exposure": "A07:2021-Identification and Authentication Failures",
}
TAXONOMY_MAP: dict[str, FindingTaxonomy] = {
    "R1-auth-weakness": FindingTaxonomy.AUTHORIZATION,
    "R2-vuln-dependency": FindingTaxonomy.DEPENDENCY,
    "R3-secret-exposure": FindingTaxonomy.SECRETS,
    "R4-access-control-risk": FindingTaxonomy.RLS,
}


def _downgrade(sev: str) -> str:
    order = _SEVERITY_ORDER
    return order[max(0, order.index(sev) - 1)] if sev in order else sev


def classify_candidate(
    *,
    candidate: FindingCandidate,
    verification_status: str,
    scanner_severities: list[str],
    evidence_count: int,
    independent_sources: int,
    contradiction: bool,
    cvss: dict[str, Any] | None = None,
) -> tuple[Classification, ClassificationConflict | None]:
    """Deterministic severity/confidence. Scanner severities are data:
    unanimously-lower + supported-only ⇒ one-level downgrade with reason;
    conflicting scanner severities ⇒ conflict + NEEDS_REVIEW (no auto-pick)."""
    from emo_cyber_agent.core.correlation import compute_confidence

    rule = candidate.rule_id.split("@")[0] if "@" in candidate.rule_id else candidate.rule_id
    provisional = candidate.provisional_severity if candidate.provisional_severity in _SEVERITY_ORDER else "info"
    uniq_scanner = sorted({s.lower() for s in scanner_severities if s})
    conflict = None
    final_sev = provisional
    basis = f"candidate provisional {provisional} + {verification_status} verification (cls-v1)"
    if len(uniq_scanner) > 1:
        conflict = ClassificationConflict(
            assessments=tuple(SeverityAssessment(severity=Severity(s) if s in _SEVERITY_ORDER else Severity.INFO, basis=f"scanner-attributed {s}", source="scanner") for s in uniq_scanner),
            note="conflicting scanner severities kept; needs review, no auto-pick",
        )
        basis += "; scanner conflict recorded, provisional kept pending review"
    elif (
        len(uniq_scanner) == 1
        and uniq_scanner[0] in _SEVERITY_ORDER
        and provisional in _SEVERITY_ORDER
        and verification_status == "supported"
        and _SEVERITY_ORDER.index(uniq_scanner[0]) < _SEVERITY_ORDER.index(provisional)
    ):
        final_sev = _downgrade(provisional)
        basis += f"; unanimous scanner {uniq_scanner[0]} below provisional with supported-only verification → downgraded with reason"
    value = compute_confidence(n_evidence=evidence_count, n_sources=independent_sources, has_conflict=contradiction)
    if verification_status == "confirmed":
        value = round(min(0.95, value + 0.1), 2)
    classification = Classification(
        category=TAXONOMY_MAP.get(rule, FindingTaxonomy.OTHER),
        severity=SeverityAssessment(severity=Severity(final_sev), basis=basis, source="core-classification", rule_version=CLASSIFICATION_VERSION),
        confidence=ConfidenceAssessment(value=value, evidence_count=evidence_count, independent_sources=independent_sources, verification_strength=verification_status, contradiction_present=contradiction, basis="evidence count + sources + verification + conflict (no model scores)"),
        cwe=CWE_MAP.get(rule),
        owasp=OWASP_MAP.get(rule),
        cvss_vector=(cvss or {}).get("vector"),
        cvss_score=(cvss or {}).get("score"),
        cvss_source=(cvss or {}).get("source"),
        explained=f"severity {final_sev}: {basis}; evidence {[candidate.candidate_id]}; verification {verification_status}; rule {rule}@{CLASSIFICATION_VERSION}",
    )
    return classification, conflict


# ---------------------------------------------------------------------------
# Promotion: candidate + verification + classification → SecurityFinding
# ---------------------------------------------------------------------------

def promote_candidate(
    *,
    candidate: FindingCandidate,
    verification_status: str,
    verification_ids: list[str] | tuple[str, ...],
    evidence_ids: list[str] | tuple[str, ...],
    observation_ids: list[str] | tuple[str, ...],
    classification: Classification,
    scope_ok: bool,
    policy_ok: bool,
    audit_id: str,
    asset_id: str | None = None,
    location: str = "",
    identity: str = "",
    remediation: Remediation | None = None,
    references: list[str] | tuple[str, ...] | None = None,
) -> SecurityFinding:
    """Builds a CONFIRMED finding ONLY through the gated path. Any shortcut
    raises instead of producing a weaker object."""
    transition_candidate_state(candidate.status, "confirmed-target")
    elig = evaluate_finding_eligibility(
        candidate=candidate, evidence_ids=list(evidence_ids), provenance_ok=True, scope_ok=scope_ok,
        verification_status=verification_status, contradiction_unresolved=False,
        candidate_status=candidate.status.value, policy_ok=policy_ok,
    )
    if elig.verdict != Eligibility.ELIGIBLE:
        raise ValueError(f"candidate not eligible: {elig.reasons}")
    fp = finding_fingerprint(audit_id=audit_id, asset_id=asset_id, category=classification.category.value, location=location, identity=identity or candidate.candidate_id, rule=candidate.rule_id)
    return SecurityFinding(
        finding_id=f"finding-{candidate.candidate_id[:8]}-{fp[:8]}",
        audit_id=audit_id,
        asset_id=asset_id,
        title=candidate.hypothesis[:200],
        description=candidate.hypothesis[:2000],
        category=classification.category,
        severity=classification.severity.severity,
        confidence=classification.confidence.value,
        status=FindingStatus.CONFIRMED,
        cwe=classification.cwe,
        owasp=classification.owasp,
        affected_locations=tuple([location] if location else []),
        evidence_ids=tuple(evidence_ids),
        observation_ids=tuple(observation_ids),
        candidate_id=candidate.candidate_id,
        verification_ids=tuple(verification_ids),
        provenance={"candidate": candidate.candidate_id, "rule": candidate.rule_id, "classification_version": CLASSIFICATION_VERSION, "finding_schema": FINDING_SCHEMA_VERSION, "policy": "strict"},
        remediation=remediation,
        references=tuple(references or []),
        observed_issue=candidate.hypothesis[:500],
        root_cause="",
        impact="UNASSESSED",
        attack_precondition="",
        fingerprint=fp,
        regression_key=regression_key(asset_id=asset_id, category=classification.category.value, location=location, identity=identity or candidate.candidate_id, rule=candidate.rule_id),
    )


def transition_candidate_state(current: str, target: str) -> str:
    """Maps ECA-T008 candidate statuses onto the gated promotion pre-path.

    Only these pre-states may ENTER verification-driven promotion; the
    CONFIRMED state itself is produced solely by promote_candidate.
    """
    allowed = {"correlated", "supported", "verifying", "needs_verification"}
    if target != "confirmed-target":
        raise ValueError(f"unknown promotion target: {target}")
    if current not in allowed:
        raise ValueError(f"candidate state {current} cannot enter confirmation")
    return target


def apply_model_suggestion(finding: SecurityFinding, suggestion: dict[str, Any]) -> SecurityFinding:
    """Model suggestions land as UNVERIFIED annotations only. Core-decided
    severity/status/evidence/scope are immutable through this path."""
    for locked in ("severity", "status", "evidence_ids", "audit_id", "candidate_id", "verification_ids", "fingerprint"):
        if locked in suggestion:
            raise ValueError(f"model cannot set {locked}")
    allowed = {k: v for k, v in suggestion.items() if k in ("title", "description", "remediation", "references", "cwe", "owasp")}
    if "cwe" in allowed and finding.cwe is not None:
        raise ValueError("model cannot override Core CWE")
    if "owasp" in allowed and finding.owasp is not None:
        raise ValueError("model cannot override Core OWASP")
    data = finding.model_dump()
    for k, v in allowed.items():
        data[k] = v
    data["provenance"] = {**finding.provenance, "model_suggestion": "unverified"}
    return SecurityFinding(**data)


def is_reportable(finding: SecurityFinding) -> tuple[bool, list[str]]:
    problems: list[str] = []
    if not finding.evidence_ids:
        problems.append("missing-evidence")
    if not finding.provenance:
        problems.append("invalid-provenance")
    if not finding.audit_id or not finding.candidate_id:
        problems.append("missing-scope")
    if finding.status not in (FindingStatus.CONFIRMED, FindingStatus.REPORTED):
        problems.append("unverified-candidate")
    if not finding.fingerprint:
        problems.append("malformed-identity")
    return (not problems, problems)
