"""Tool pack errors — POST-RC-007."""

from __future__ import annotations

from enum import StrEnum


class ToolPackErrorCode(StrEnum):
    NOT_FOUND = "TOOL_PACK_NOT_FOUND"
    INVALID = "TOOL_PACK_INVALID"
    VERSION_INVALID = "TOOL_PACK_VERSION_INVALID"
    REFERENCE_INVALID = "TOOL_PACK_REFERENCE_INVALID"
    CAPABILITY_UNKNOWN = "TOOL_PACK_CAPABILITY_UNKNOWN"
    CAPABILITY_ESCALATION = "TOOL_PACK_CAPABILITY_ESCALATION"
    SHELL_SEMANTICS = "TOOL_PACK_SHELL_SEMANTICS"
    INPUT_REJECTED = "TOOL_PACK_INPUT_REJECTED"
    BINDING_MISMATCH = "TOOL_PACK_BINDING_MISMATCH"
    STALE_SNAPSHOT = "TOOL_PACK_STALE_SNAPSHOT"
    VERSION_UNSUPPORTED = "TOOL_PACK_VERSION_UNSUPPORTED"
    TOOL_UNAVAILABLE = "TOOL_PACK_TOOL_UNAVAILABLE"
    NETWORK_UNAVAILABLE = "TOOL_PACK_NETWORK_UNAVAILABLE"
    POLICY_DENIED = "TOOL_PACK_POLICY_DENIED"
    UNSAFE = "TOOL_PACK_UNSAFE"
    UNTRUSTED = "TOOL_PACK_UNTRUSTED"
    DUPLICATE = "TOOL_PACK_DUPLICATE"
    HEALTH_UNKNOWN = "TOOL_PACK_HEALTH_UNKNOWN"


class ToolPackError(Exception):
    def __init__(self, code: ToolPackErrorCode, message: str):
        super().__init__(f"{code.value}: {message}")
        self.code = code
