"""Security knowledge errors — POST-RC-011."""

from __future__ import annotations

from enum import StrEnum


class KnowledgeErrorCode(StrEnum):
    INVALID = "KNOWLEDGE_INVALID"
    SCOPE_DENIED = "KNOWLEDGE_SCOPE_DENIED"
    CROSS_AUDIT = "KNOWLEDGE_CROSS_AUDIT"
    CROSS_PROJECT = "KNOWLEDGE_CROSS_PROJECT"
    CROSS_SNAPSHOT = "KNOWLEDGE_CROSS_SNAPSHOT"
    IDENTITY_FORGED = "KNOWLEDGE_IDENTITY_FORGED"
    PROVENANCE_FORGED = "KNOWLEDGE_PROVENANCE_FORGED"
    SECRET_MATERIAL = "KNOWLEDGE_SECRET_MATERIAL"
    BANNED_CONTENT = "KNOWLEDGE_BANNED_CONTENT"
    STALE_RECORD = "KNOWLEDGE_STALE_RECORD"
    INCOMPATIBLE_RECORD = "KNOWLEDGE_INCOMPATIBLE_RECORD"
    QUERY_REJECTED = "KNOWLEDGE_QUERY_REJECTED"
    NOT_FOUND = "KNOWLEDGE_NOT_FOUND"
    DUPLICATE_REGION = "KNOWLEDGE_DUPLICATE_REGION"
    VERDICT_CAPPED = "KNOWLEDGE_VERDICT_CAPPED"


class KnowledgeError(Exception):
    def __init__(self, code: KnowledgeErrorCode, message: str):
        super().__init__(f"{code.value}: {message}")
        self.code = code
