"""Secure, versioned, discoverable extension ecosystem — POST-RC-014.

Four separations hold across this package and are enforced by tests:

* **discovery != trust** — metadata is found; trust is evaluated by the
  host from source class, validation, provenance and verification;
* **installation != permission** — pip/pipx install distributions; EMO
  grants nothing and performs no install, upgrade or removal;
* **registration != execution authority** — a registry entry describes
  content and never runs it; loading is an explicit host step;
* **metadata != security verdict** — a manifest is data, never a
  Finding, a severity, a capability or a policy decision.

The layer grants no capability, never bypasses ``PolicyEngine``, never
executes a tool or a verification, never creates or mutates a Finding,
never widens Task/Playbook scope, never executes code during discovery,
never turns plugin metadata into executable instructions and never
depends on a model provider.
"""

from __future__ import annotations

# constants
from emo_cyber_agent.extensions.compatibility import (
    CompatibilityResult,
    HostProfile,
    check_compatibility,
    host_profile,
    python_satisfies,
    satisfies,
    supports_api,
)
from emo_cyber_agent.extensions.conflicts import (
    ExtensionConflict,
    detect_cycles,
    detect_duplicates,
    provider_conflicts,
)
from emo_cyber_agent.extensions.errors import ExtensionError, ExtensionErrorCode
from emo_cyber_agent.extensions.manifest import (
    MANIFEST_KEYS,
    compute_manifest_digest,
    find_self_declared_trust,
    load_manifest_file,
    load_manifest_text,
    manifest_from_dict,
    manifest_to_dict,
    normalize_manifest_dict,
    validate_against_schema,
)

# classes / enums
from emo_cyber_agent.extensions.registry import (
    ALLOWED_QUERIES,
    ExtensionRegistry,
    RegisteredExtension,
)
from emo_cyber_agent.extensions.resolver import (
    ExtensionResolver,
    Resolution,
    ResolutionRequest,
)
from emo_cyber_agent.extensions.spec import (
    ALLOWED_DECLARED_CAPABILITIES,
    ALLOWED_TRANSITIONS,
    CAPABILITY_ALLOWED_FOR,
    CONTRACT_VERSION,
    DATA_ACCESS_TOKENS,
    DECLARATIVE_TYPES,
    EXECUTABLE_TYPES,
    EXTENSION_API_VERSION,
    EXTENSION_TYPES,
    FORBIDDEN_DECLARATIONS,
    FORBIDDEN_SECRET_DECLARATIONS,
    SCHEMA_VERSION,
    SELF_DECLARED_TRUST_KEYS,
    TRUSTED_STATES,
    DatasetClassification,
    ExtensionArtifact,
    ExtensionCapabilityDeclaration,
    ExtensionCompatibility,
    ExtensionDeclaredCapability,
    ExtensionConflictKind,
    ExtensionDependency,
    ExtensionDependencyType,
    ExtensionEntrypoint,
    ExtensionEntrypointKind,
    ExtensionHealth,
    ExtensionHealthStatus,
    ExtensionIdentity,
    ExtensionLifecycle,
    ExtensionManifest,
    ExtensionProvenance,
    ExtensionResource,
    ExtensionResourceKind,
    ExtensionSecurityProfile,
    ExtensionSourceClass,
    ExtensionTrust,
    ExtensionTrustState,
    ExtensionType,
    ExtensionVersion,
    NetworkRequirement,
    ProcessRequirement,
    ProvenanceStatus,
    SecretDeclaration,
    VersionPolicy,
    extension_types,
    manifest_identity_digest,
    parse_version,
    split_constraint,
    version_key,
)
from emo_cyber_agent.extensions.trust import (
    OFFICIAL_PUBLISHERS,
    evaluate_trust,
    provenance_complete,
    trust_allows_load,
    trust_allows_registration,
)

# functions
from emo_cyber_agent.extensions.catalog import (
    OFFICIAL_PUBLISHER,
    READ_ACTIONS,
    MaterializedContent,
    build_read_registry,
    content_resource,
    extension_roots,
    load_official_extensions,
    materialize_content,
    materialize_evaluation_dataset,
    materialize_playbook,
    materialize_report_template,
    materialize_skill,
    materialize_skill_pack,
    materialize_task,
    materialize_threat_method,
    materialize_tool_pack,
    materialize_verification_adapter,
    materialize_verification_strategy,
    read_extensions,
    read_resource_text,
    resolve_resource_path,
    verify_extension_contract,
)
from emo_cyber_agent.extensions.discovery import (
    ENTRY_POINT_GROUP,
    MANIFEST_GLOBS,
    DiscoveredSource,
    DiscoveryReport,
    DistributionRecord,
    EntryPointRef,
    discover_directory,
    discover_distributions,
    discover_entry_points,
    discover_manifest_file,
    parse_entry_target,
    source_from_dict,
)
from emo_cyber_agent.extensions.loader import (
    ExtensionLoader,
    LoadReport,
    default_importer,
)
from emo_cyber_agent.extensions.provenance import (
    ProvenanceAssessment,
    artifact_digest_of,
    assess_provenance,
    provenance_digest,
    verify_artifact_digest,
)
from emo_cyber_agent.extensions.validator import (
    ExtensionValidation,
    ExtensionValidator,
    flag_authority_language,
    validate_manifest,
)

__all__ = [
    # constants
    "ALLOWED_DECLARED_CAPABILITIES",
    "ALLOWED_QUERIES",
    "ALLOWED_TRANSITIONS",
    "CAPABILITY_ALLOWED_FOR",
    "CONTRACT_VERSION",
    "CONTENT_RESOURCE_ID",
    "DATA_ACCESS_TOKENS",
    "DECLARATIVE_TYPES",
    "ENTRY_POINT_GROUP",
    "EXECUTABLE_TYPES",
    "EXTENSION_API_VERSION",
    "EXTENSION_TYPES",
    "FORBIDDEN_DECLARATIONS",
    "FORBIDDEN_SECRET_DECLARATIONS",
    "MANIFEST_GLOBS",
    "MANIFEST_KEYS",
    "OFFICIAL_PUBLISHER",
    "OFFICIAL_PUBLISHERS",
    "READ_ACTIONS",
    "SCHEMA_VERSION",
    "SELF_DECLARED_TRUST_KEYS",
    "TRUSTED_STATES",
    # classes / enums
    "CompatibilityResult",
    "DatasetClassification",
    "DiscoveredSource",
    "DiscoveryReport",
    "DistributionRecord",
    "EntryPointRef",
    "ExtensionArtifact",
    "ExtensionCapabilityDeclaration",
    "ExtensionCompatibility",
    "ExtensionConflict",
    "ExtensionConflictKind",
    "ExtensionDeclaredCapability",
    "ExtensionDependency",
    "ExtensionDependencyType",
    "ExtensionEntrypoint",
    "ExtensionEntrypointKind",
    "ExtensionError",
    "ExtensionErrorCode",
    "ExtensionHealth",
    "ExtensionHealthStatus",
    "ExtensionIdentity",
    "ExtensionLifecycle",
    "ExtensionLoader",
    "ExtensionManifest",
    "ExtensionProvenance",
    "ExtensionRegistry",
    "ExtensionResolver",
    "ExtensionResource",
    "ExtensionResourceKind",
    "ExtensionSecurityProfile",
    "ExtensionSourceClass",
    "ExtensionTrust",
    "ExtensionTrustState",
    "ExtensionType",
    "ExtensionValidation",
    "ExtensionValidator",
    "ExtensionVersion",
    "HostProfile",
    "LoadReport",
    "MaterializedContent",
    "NetworkRequirement",
    "ProcessRequirement",
    "ProvenanceAssessment",
    "ProvenanceStatus",
    "RegisteredExtension",
    "Resolution",
    "ResolutionRequest",
    "SecretDeclaration",
    "VersionPolicy",
    # functions
    "artifact_digest_of",
    "assess_provenance",
    "build_read_registry",
    "check_compatibility",
    "compute_manifest_digest",
    "content_resource",
    "default_importer",
    "detect_cycles",
    "detect_duplicates",
    "discover_directory",
    "discover_distributions",
    "discover_entry_points",
    "discover_manifest_file",
    "evaluate_trust",
    "extension_roots",
    "extension_types",
    "find_self_declared_trust",
    "flag_authority_language",
    "host_profile",
    "load_manifest_file",
    "load_manifest_text",
    "load_official_extensions",
    "manifest_from_dict",
    "manifest_identity_digest",
    "manifest_to_dict",
    "materialize_content",
    "materialize_evaluation_dataset",
    "materialize_playbook",
    "materialize_report_template",
    "materialize_skill",
    "materialize_skill_pack",
    "materialize_task",
    "materialize_threat_method",
    "materialize_tool_pack",
    "materialize_verification_adapter",
    "materialize_verification_strategy",
    "normalize_manifest_dict",
    "parse_entry_target",
    "parse_version",
    "provider_conflicts",
    "provenance_complete",
    "provenance_digest",
    "python_satisfies",
    "read_extensions",
    "read_resource_text",
    "resolve_resource_path",
    "satisfies",
    "source_from_dict",
    "split_constraint",
    "supports_api",
    "trust_allows_load",
    "trust_allows_registration",
    "validate_against_schema",
    "validate_manifest",
    "verify_artifact_digest",
    "verify_extension_contract",
    "version_key",
]
