"""Threat modeling — POST-RC-009.

Auditable, snapshot-bound security representations: system model,
attack surface, trust boundaries, threat hypotheses, controls,
verification handoffs. No findings, no severity, no confirmation,
no execution, no remediation.
"""

from emo_cyber_agent.threat_modeling.attack_surface import build_attack_surface
from emo_cyber_agent.threat_modeling.controls import coverage_for, expected_controls, observe_controls
from emo_cyber_agent.threat_modeling.delta import diff_threat_models
from emo_cyber_agent.threat_modeling.errors import ThreatModelError, ThreatModelErrorCode
from emo_cyber_agent.threat_modeling.methods import get_method, register_method, registered_methods, rules_for
from emo_cyber_agent.threat_modeling.paths import find_attack_paths
from emo_cyber_agent.threat_modeling.provenance import build_threat_provenance
from emo_cyber_agent.threat_modeling.queries import ALLOWED_SURFACE_QUERIES, ThreatQueryPort
from emo_cyber_agent.threat_modeling.service import ThreatModelingService
from emo_cyber_agent.threat_modeling.spec import (
    BOUNDARY_BASIS,
    BOUNDARY_KINDS,
    CONTROL_KINDS,
    CONTROL_STATUS,
    COVERAGE_STATES,
    DELTA_KINDS,
    HYPOTHESIS_STATUS,
    PATH_CLASSES,
    SURFACE_CATEGORIES,
    AttackPath,
    AttackSurface,
    AttackSurfaceElement,
    AttackSurfaceRelation,
    EntryPoint,
    ExitPoint,
    Mitigation,
    ModelCoverage,
    PackTrust,
    SecurityControl,
    SystemAsset,
    SystemComponent,
    SystemDataFlow,
    SystemDataStore,
    SystemModel,
    SystemProcess,
    ThreatAssessment,
    ThreatCategory,
    ThreatDeltaEntry,
    ThreatHypothesis,
    ThreatMethod,
    ThreatModel,
    ThreatModelDelta,
    ThreatPattern,
    ThreatRule,
    ThreatScenario,
    ThreatTemplateConfig,
    ThreatVerificationHandoff,
    assert_no_threat_verdicts,
    canonical_digest,
    stable_id,
)
from emo_cyber_agent.threat_modeling.stride import STRIDE_SPEC, elicit_stride
from emo_cyber_agent.threat_modeling.system_model import build_system_model
from emo_cyber_agent.threat_modeling.threats import build_threat_scenarios

__all__ = [
    "ALLOWED_SURFACE_QUERIES",
    "BOUNDARY_BASIS",
    "BOUNDARY_KINDS",
    "CONTROL_KINDS",
    "CONTROL_STATUS",
    "COVERAGE_STATES",
    "DELTA_KINDS",
    "HYPOTHESIS_STATUS",
    "PATH_CLASSES",
    "STRIDE_SPEC",
    "SURFACE_CATEGORIES",
    "AttackPath",
    "AttackSurface",
    "AttackSurfaceElement",
    "AttackSurfaceRelation",
    "EntryPoint",
    "ExitPoint",
    "Mitigation",
    "ModelCoverage",
    "PackTrust",
    "SecurityControl",
    "SystemAsset",
    "SystemComponent",
    "SystemDataFlow",
    "SystemDataStore",
    "SystemModel",
    "SystemProcess",
    "ThreatAssessment",
    "ThreatCategory",
    "ThreatDeltaEntry",
    "ThreatHypothesis",
    "ThreatMethod",
    "ThreatModel",
    "ThreatModelDelta",
    "ThreatModelError",
    "ThreatModelErrorCode",
    "ThreatModelingService",
    "ThreatPattern",
    "ThreatQueryPort",
    "ThreatRule",
    "ThreatScenario",
    "ThreatTemplateConfig",
    "ThreatVerificationHandoff",
    "assert_no_threat_verdicts",
    "build_attack_surface",
    "build_system_model",
    "build_threat_provenance",
    "build_threat_scenarios",
    "canonical_digest",
    "stable_id",
    "coverage_for",
    "diff_threat_models",
    "elicit_stride",
    "expected_controls",
    "find_attack_paths",
    "get_method",
    "observe_controls",
    "register_method",
    "registered_methods",
    "rules_for",
]
